// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_change_control

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64default"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"regexp"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func ChangeControlResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"admin_status": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The admin status of the change control. The API requires at least one of `orchestration` or `nd_managed_fabrics` to be `true` when this is enabled. Defaults to `false` when not specified in the configuration.",
				MarkdownDescription: "The admin status of the change control. The API requires at least one of `orchestration` or `nd_managed_fabrics` to be `true` when this is enabled. Defaults to `false` when not specified in the configuration.",
				Default:             booldefault.StaticBool(false),
			},
			"allow_self_approval": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The self approval status of the change control for an orchestration action to approve that ticket. Defaults to `true` when not specified in the configuration.",
				MarkdownDescription: "The self approval status of the change control for an orchestration action to approve that ticket. Defaults to `true` when not specified in the configuration.",
				Default:             booldefault.StaticBool(true),
			},
			"bypass_telemetry_change_control": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Bypasses change control for telemetry operations in Nexus Dashboard managed fabrics. Defaults to `false` when not specified in the configuration.",
				MarkdownDescription: "Bypasses change control for telemetry operations in Nexus Dashboard managed fabrics. Defaults to `false` when not specified in the configuration.",
				Default:             booldefault.StaticBool(false),
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "The fixed Terraform identifier for the Change Control settings is changeControl.",
				MarkdownDescription: "The fixed Terraform identifier for the Change Control settings is changeControl.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"nd_managed_fabrics": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The Nexus Dashboard managed fabrics status of the change control. Defaults to `false` when not specified in the configuration.",
				MarkdownDescription: "The Nexus Dashboard managed fabrics status of the change control. Defaults to `false` when not specified in the configuration.",
				Default:             booldefault.StaticBool(false),
			},
			"number_of_approvers": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "The number of approvals required for orchestration templates. This applies when `orchestration` is enabled and must be between `1` and `10`. Defaults to `1` when not specified in the configuration.",
				MarkdownDescription: "The number of approvals required for orchestration templates. This applies when `orchestration` is enabled and must be between `1` and `10`. Defaults to `1` when not specified in the configuration.",
				Validators: []validator.Int64{
					int64validator.Between(1, 10),
				},
				Default: int64default.StaticInt64(1),
			},
			"orchestration": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The orchestration status of the change control for ACI fabrics. Defaults to `false` when not specified in the configuration.",
				MarkdownDescription: "The orchestration status of the change control for ACI fabrics. Defaults to `false` when not specified in the configuration.",
				Default:             booldefault.StaticBool(false),
			},
			"ticket_name_prefix": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The prefix of the ticket name for the change control. The ticket name must start with a letter followed by one or more letters, digits, underscores, or hyphens. Defaults to `TICKET_` when not specified in the configuration.",
				MarkdownDescription: "The prefix of the ticket name for the change control. The ticket name must start with a letter followed by one or more letters, digits, underscores, or hyphens. Defaults to `TICKET_` when not specified in the configuration.",
				Validators: []validator.String{
					stringvalidator.LengthBetween(1, 255), stringvalidator.RegexMatches(regexp.MustCompile(`^[a-zA-Z][a-zA-Z0-9_-]+$`), "must start with a letter and contain only letters, digits, underscores, or hyphens"),
				},
				Default: stringdefault.StaticString("TICKET_"),
			},
		},
		Description:         "Manages change control system settings for Nexus Dashboard.\n\nChange Control is a built-in Nexus Dashboard setting rather than a new object.\nDuring Terraform creation, import the existing Change Control object first,\nto see differences before applying changes.\n\nDuring destroy, Terraform uses PUT to restore the default Change Control settings\nbefore removing the resource from state. The built-in object remains in Nexus Dashboard.\n\nIf you want to stop managing Change Control without resetting its current Nexus Dashboard\nsettings, remove the resource from Terraform state with `terraform state rm\nnd_change_control.<name>` and remove the resource block from the configuration. This\nbypasses the provider destroy operation and leaves the Nexus Dashboard settings unchanged.    \n",
		MarkdownDescription: "Manages change control system settings for Nexus Dashboard.\n\nChange Control is a built-in Nexus Dashboard setting rather than a new object.\nDuring Terraform creation, import the existing Change Control object first,\nto see differences before applying changes.\n\nDuring destroy, Terraform uses PUT to restore the default Change Control settings\nbefore removing the resource from state. The built-in object remains in Nexus Dashboard.\n\nIf you want to stop managing Change Control without resetting its current Nexus Dashboard\nsettings, remove the resource from Terraform state with `terraform state rm\nnd_change_control.<name>` and remove the resource block from the configuration. This\nbypasses the provider destroy operation and leaves the Nexus Dashboard settings unchanged.    \n",
	}
}

type ChangeControlModel struct {
	AdminStatus                  types.Bool   `tfsdk:"admin_status"`
	AllowSelfApproval            types.Bool   `tfsdk:"allow_self_approval"`
	BypassTelemetryChangeControl types.Bool   `tfsdk:"bypass_telemetry_change_control"`
	Id                           types.String `tfsdk:"id"`
	NdManagedFabrics             types.Bool   `tfsdk:"nd_managed_fabrics"`
	NumberOfApprovers            types.Int64  `tfsdk:"number_of_approvers"`
	Orchestration                types.Bool   `tfsdk:"orchestration"`
	TicketNamePrefix             types.String `tfsdk:"ticket_name_prefix"`
}
