// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_config_deploy

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/objectdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func ConfigDeployResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"always_execute": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "When true, force the resource to show as an update on every `terraform apply`, ensuring that the `behaviour.execute_on_update` logic runs on every apply. Internally, Read resets this to false in state so Terraform always detects a diff. When false (default), the resource settles after initial creation and only re-executes when other attributes change.\n",
				MarkdownDescription: "When true, force the resource to show as an update on every `terraform apply`, ensuring that the `behaviour.execute_on_update` logic runs on every apply. Internally, Read resets this to false in state so Terraform always detects a diff. When false (default), the resource settles after initial creation and only re-executes when other attributes change.\n",
				Default:             booldefault.StaticBool(false),
			},
			"behaviour": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"execute_on_create": schema.BoolAttribute{
						Optional:            true,
						Computed:            true,
						Description:         "When true, execute config-save and/or deploy when the resource is created. When false, resource creation only writes Terraform state without performing any operations on ND.\n",
						MarkdownDescription: "When true, execute config-save and/or deploy when the resource is created. When false, resource creation only writes Terraform state without performing any operations on ND.\n",
						Default:             booldefault.StaticBool(true),
					},
					"execute_on_destroy": schema.BoolAttribute{
						Optional:            true,
						Computed:            true,
						Description:         "When true, execute config-save and/or deploy when the resource is destroyed. Useful for deploying configuration removal to switches. This flag is read from Terraform state, not from the current configuration. If you change this from false to true, you must run `terraform apply` before `terraform destroy` so the new value is persisted to state.\n",
						MarkdownDescription: "When true, execute config-save and/or deploy when the resource is destroyed. Useful for deploying configuration removal to switches. This flag is read from Terraform state, not from the current configuration. If you change this from false to true, you must run `terraform apply` before `terraform destroy` so the new value is persisted to state.\n",
						Default:             booldefault.StaticBool(false),
					},
					"execute_on_update": schema.BoolAttribute{
						Optional:            true,
						Computed:            true,
						Description:         "When true, execute config-save and/or deploy when the resource is updated. Commonly used with `always_execute = true` to re-execute on every apply.\n",
						MarkdownDescription: "When true, execute config-save and/or deploy when the resource is updated. Commonly used with `always_execute = true` to re-execute on every apply.\n",
						Default:             booldefault.StaticBool(true),
					},
				},
				CustomType: BehaviourType{
					ObjectType: types.ObjectType{
						AttrTypes: BehaviourValue{}.AttributeTypes(ctx),
					},
				},
				Optional:            true,
				Computed:            true,
				Description:         "Controls when the config-save and deploy operations are executed during the Terraform resource lifecycle. Note that setting all controls to false will make this resource a no-op.\n",
				MarkdownDescription: "Controls when the config-save and deploy operations are executed during the Terraform resource lifecycle. Note that setting all controls to false will make this resource a no-op.\n",
				Default:             objectdefault.StaticValue(types.ObjectValueMust(map[string]attr.Type{"execute_on_create": types.BoolType, "execute_on_update": types.BoolType, "execute_on_destroy": types.BoolType}, map[string]attr.Value{"execute_on_create": types.BoolValue(true), "execute_on_update": types.BoolValue(true), "execute_on_destroy": types.BoolValue(false)})),
			},
			"config_save": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "When true, perform a config-save (recalculate) operation on the fabric. Can be used independently or together with `deploy`. When both are true, config-save runs first. Also known as recalculate in the API.\n",
				MarkdownDescription: "When true, perform a config-save (recalculate) operation on the fabric. Can be used independently or together with `deploy`. When both are true, config-save runs first. Also known as recalculate in the API.\n",
				Default:             booldefault.StaticBool(false),
			},
			"deploy": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "When true, deploy the fabric configuration to switches. Can be used independently or together with `config_save`. At least one of `deploy` or `config_save` must be true.\n",
				MarkdownDescription: "When true, deploy the fabric configuration to switches. Can be used independently or together with `config_save`. At least one of `deploy` or `config_save` must be true.\n",
				Default:             booldefault.StaticBool(false),
			},
			"fabric_name": schema.StringAttribute{
				Required:            true,
				Description:         "Name of the fabric to perform config-save and/or deploy on",
				MarkdownDescription: "Name of the fabric to perform config-save and/or deploy on",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"force_show_run": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "When true, fetch the latest running configuration from each switch instead of using the cached version before deployment.\n",
				MarkdownDescription: "When true, fetch the latest running configuration from each switch instead of using the cached version before deployment.\n",
				Default:             booldefault.StaticBool(false),
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "The unique identifier of the config_deploy resource",
				MarkdownDescription: "The unique identifier of the config_deploy resource",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"include_all_fabric_group_switches": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "When true and the target is a fabric group, deploy changes to switches in all member fabrics. Only applicable for fabric-wide deploy.\n",
				MarkdownDescription: "When true and the target is a fabric group, deploy changes to switches in all member fabrics. Only applicable for fabric-wide deploy.\n",
				Default:             booldefault.StaticBool(false),
			},
			"status": schema.StringAttribute{
				Computed:            true,
				Description:         "Status message from the last config-save and/or deploy operation. Read-only, assembled from API responses after the operation completes. When behaviour flags skip execution, this field is unset.\n",
				MarkdownDescription: "Status message from the last config-save and/or deploy operation. Read-only, assembled from API responses after the operation completes. When behaviour flags skip execution, this field is unset.\n",
			},
			"switch_ids": schema.SetAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Description:         "List of switch serial numbers/IP addresses to deploy configuration to. Both IP addresses and serial numbers are accepted. Use `[\"ALL\"]` or omit to perform a fabric-wide deploy.\n",
				MarkdownDescription: "List of switch serial numbers/IP addresses to deploy configuration to. Both IP addresses and serial numbers are accepted. Use `[\"ALL\"]` or omit to perform a fabric-wide deploy.\n",
			},
			"ticket_id": schema.StringAttribute{
				Optional:            true,
				Description:         "Change Control ticket ID to associate with the config-save operation. Must begin with a letter; remaining characters may be letters, numbers, underscores, or hyphens. Length: 1–64 characters.\n",
				MarkdownDescription: "Change Control ticket ID to associate with the config-save operation. Must begin with a letter; remaining characters may be letters, numbers, underscores, or hyphens. Length: 1–64 characters.\n",
			},
		},
		Description:         "Triggers fabric configuration save (recalculate) and/or deployment operations on an ND-managed fabric. This is an action resource — it executes config-save and deploy operations rather than managing a persistent API object.\n",
		MarkdownDescription: "Triggers fabric configuration save (recalculate) and/or deployment operations on an ND-managed fabric. This is an action resource — it executes config-save and deploy operations rather than managing a persistent API object.\n",
	}
}

type ConfigDeployModel struct {
	AlwaysExecute                 types.Bool     `tfsdk:"always_execute"`
	Behaviour                     BehaviourValue `tfsdk:"behaviour"`
	ConfigSave                    types.Bool     `tfsdk:"config_save"`
	Deploy                        types.Bool     `tfsdk:"deploy"`
	FabricName                    types.String   `tfsdk:"fabric_name"`
	ForceShowRun                  types.Bool     `tfsdk:"force_show_run"`
	Id                            types.String   `tfsdk:"id"`
	IncludeAllFabricGroupSwitches types.Bool     `tfsdk:"include_all_fabric_group_switches"`
	Status                        types.String   `tfsdk:"status"`
	SwitchIds                     types.Set      `tfsdk:"switch_ids"`
	TicketId                      types.String   `tfsdk:"ticket_id"`
}

var _ basetypes.ObjectTypable = BehaviourType{}

type BehaviourType struct {
	basetypes.ObjectType
}

func (t BehaviourType) Equal(o attr.Type) bool {
	other, ok := o.(BehaviourType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t BehaviourType) String() string {
	return "BehaviourType"
}

func (t BehaviourType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	executeOnCreateAttribute, ok := attributes["execute_on_create"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`execute_on_create is missing from object`)

		return nil, diags
	}

	executeOnCreateVal, ok := executeOnCreateAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`execute_on_create expected to be basetypes.BoolValue, was: %T`, executeOnCreateAttribute))
	}

	executeOnDestroyAttribute, ok := attributes["execute_on_destroy"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`execute_on_destroy is missing from object`)

		return nil, diags
	}

	executeOnDestroyVal, ok := executeOnDestroyAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`execute_on_destroy expected to be basetypes.BoolValue, was: %T`, executeOnDestroyAttribute))
	}

	executeOnUpdateAttribute, ok := attributes["execute_on_update"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`execute_on_update is missing from object`)

		return nil, diags
	}

	executeOnUpdateVal, ok := executeOnUpdateAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`execute_on_update expected to be basetypes.BoolValue, was: %T`, executeOnUpdateAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return BehaviourValue{
		ExecuteOnCreate:  executeOnCreateVal,
		ExecuteOnDestroy: executeOnDestroyVal,
		ExecuteOnUpdate:  executeOnUpdateVal,
		state:            attr.ValueStateKnown,
	}, diags
}

func NewBehaviourValueNull() BehaviourValue {
	return BehaviourValue{
		state: attr.ValueStateNull,
	}
}

func NewBehaviourValueUnknown() BehaviourValue {
	return BehaviourValue{
		state: attr.ValueStateUnknown,
	}
}

func NewBehaviourValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (BehaviourValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing BehaviourValue Attribute Value",
				"While creating a BehaviourValue value, a missing attribute value was detected. "+
					"A BehaviourValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("BehaviourValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid BehaviourValue Attribute Type",
				"While creating a BehaviourValue value, an invalid attribute value was detected. "+
					"A BehaviourValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("BehaviourValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("BehaviourValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra BehaviourValue Attribute Value",
				"While creating a BehaviourValue value, an extra attribute value was detected. "+
					"A BehaviourValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra BehaviourValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewBehaviourValueUnknown(), diags
	}

	executeOnCreateAttribute, ok := attributes["execute_on_create"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`execute_on_create is missing from object`)

		return NewBehaviourValueUnknown(), diags
	}

	executeOnCreateVal, ok := executeOnCreateAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`execute_on_create expected to be basetypes.BoolValue, was: %T`, executeOnCreateAttribute))
	}

	executeOnDestroyAttribute, ok := attributes["execute_on_destroy"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`execute_on_destroy is missing from object`)

		return NewBehaviourValueUnknown(), diags
	}

	executeOnDestroyVal, ok := executeOnDestroyAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`execute_on_destroy expected to be basetypes.BoolValue, was: %T`, executeOnDestroyAttribute))
	}

	executeOnUpdateAttribute, ok := attributes["execute_on_update"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`execute_on_update is missing from object`)

		return NewBehaviourValueUnknown(), diags
	}

	executeOnUpdateVal, ok := executeOnUpdateAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`execute_on_update expected to be basetypes.BoolValue, was: %T`, executeOnUpdateAttribute))
	}

	if diags.HasError() {
		return NewBehaviourValueUnknown(), diags
	}

	return BehaviourValue{
		ExecuteOnCreate:  executeOnCreateVal,
		ExecuteOnDestroy: executeOnDestroyVal,
		ExecuteOnUpdate:  executeOnUpdateVal,
		state:            attr.ValueStateKnown,
	}, diags
}

func NewBehaviourValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) BehaviourValue {
	object, diags := NewBehaviourValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewBehaviourValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t BehaviourType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewBehaviourValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewBehaviourValueUnknown(), nil
	}

	if in.IsNull() {
		return NewBehaviourValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewBehaviourValueMust(BehaviourValue{}.AttributeTypes(ctx), attributes), nil
}

func (t BehaviourType) ValueType(ctx context.Context) attr.Value {
	return BehaviourValue{}
}

var _ basetypes.ObjectValuable = BehaviourValue{}

type BehaviourValue struct {
	ExecuteOnCreate  basetypes.BoolValue `tfsdk:"execute_on_create"`
	ExecuteOnDestroy basetypes.BoolValue `tfsdk:"execute_on_destroy"`
	ExecuteOnUpdate  basetypes.BoolValue `tfsdk:"execute_on_update"`
	state            attr.ValueState
}

func (v BehaviourValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 3)

	var val tftypes.Value
	var err error

	attrTypes["execute_on_create"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["execute_on_destroy"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["execute_on_update"] = basetypes.BoolType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 3)

		val, err = v.ExecuteOnCreate.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["execute_on_create"] = val

		val, err = v.ExecuteOnDestroy.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["execute_on_destroy"] = val

		val, err = v.ExecuteOnUpdate.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["execute_on_update"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v BehaviourValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v BehaviourValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v BehaviourValue) String() string {
	return "BehaviourValue"
}

func (v BehaviourValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"execute_on_create":  basetypes.BoolType{},
		"execute_on_destroy": basetypes.BoolType{},
		"execute_on_update":  basetypes.BoolType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"execute_on_create":  v.ExecuteOnCreate,
			"execute_on_destroy": v.ExecuteOnDestroy,
			"execute_on_update":  v.ExecuteOnUpdate,
		})

	return objVal, diags
}

func (v BehaviourValue) Equal(o attr.Value) bool {
	other, ok := o.(BehaviourValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.ExecuteOnCreate.Equal(other.ExecuteOnCreate) {
		return false
	}

	if !v.ExecuteOnDestroy.Equal(other.ExecuteOnDestroy) {
		return false
	}

	if !v.ExecuteOnUpdate.Equal(other.ExecuteOnUpdate) {
		return false
	}

	return true
}

func (v BehaviourValue) Type(ctx context.Context) attr.Type {
	return BehaviourType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v BehaviourValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"execute_on_create":  basetypes.BoolType{},
		"execute_on_destroy": basetypes.BoolType{},
		"execute_on_update":  basetypes.BoolType{},
	}
}
