// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_config_deploy

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/objectdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func ConfigDeployResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"always_deploy": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "When false (default), the operations are executed only once during the initial create and are not re-executed on subsequent `terraform apply` runs. When true, the operations are always executed on every apply, which shows as an update to the resource in the plan.\n",
				MarkdownDescription: "When false (default), the operations are executed only once during the initial create and are not re-executed on subsequent `terraform apply` runs. When true, the operations are always executed on every apply, which shows as an update to the resource in the plan.\n",
				Default:             booldefault.StaticBool(false),
			},
			"behaviour": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"deploy_on_create": schema.BoolAttribute{
						Optional:            true,
						Computed:            true,
						Description:         "When true, execute config-save and/or deploy when the resource is created.\n",
						MarkdownDescription: "When true, execute config-save and/or deploy when the resource is created.\n",
						Default:             booldefault.StaticBool(true),
					},
					"deploy_on_destroy": schema.BoolAttribute{
						Optional:            true,
						Computed:            true,
						Description:         "When true, execute config-save and/or deploy when the resource is destroyed. Useful for deploying configuration removal to switches.\n",
						MarkdownDescription: "When true, execute config-save and/or deploy when the resource is destroyed. Useful for deploying configuration removal to switches.\n",
						Default:             booldefault.StaticBool(false),
					},
					"deploy_on_update": schema.BoolAttribute{
						Optional:            true,
						Computed:            true,
						Description:         "When true, execute config-save and/or deploy when the resource is updated.\n",
						MarkdownDescription: "When true, execute config-save and/or deploy when the resource is updated.\n",
						Default:             booldefault.StaticBool(true),
					},
				},
				CustomType: BehaviourType{
					ObjectType: types.ObjectType{
						AttrTypes: BehaviourValue{}.AttributeTypes(ctx),
					},
				},
				Optional:            true,
				Computed:            true,
				Description:         "Controls when the config-save and deploy operations are executed during the Terraform resource lifecycle.\n",
				MarkdownDescription: "Controls when the config-save and deploy operations are executed during the Terraform resource lifecycle.\n",
				Default:             objectdefault.StaticValue(types.ObjectValueMust(map[string]attr.Type{"deploy_on_create": types.BoolType, "deploy_on_update": types.BoolType, "deploy_on_destroy": types.BoolType}, map[string]attr.Value{"deploy_on_create": types.BoolValue(true), "deploy_on_update": types.BoolValue(true), "deploy_on_destroy": types.BoolValue(false)})),
			},
			"config_save": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "When true, perform a config-save (recalculate) operation on the fabric before deployment. Also known as recalculate in the API.\n",
				MarkdownDescription: "When true, perform a config-save (recalculate) operation on the fabric before deployment. Also known as recalculate in the API.\n",
				Default:             booldefault.StaticBool(false),
			},
			"deploy": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "When true, deploy the fabric configuration to switches after config-save. At least one of `deploy` or `config_save` must be true.\n",
				MarkdownDescription: "When true, deploy the fabric configuration to switches after config-save. At least one of `deploy` or `config_save` must be true.\n",
				Default:             booldefault.StaticBool(false),
			},
			"fabric_name": schema.StringAttribute{
				Required:            true,
				Description:         "Name of the fabric to perform config-save and/or deploy on",
				MarkdownDescription: "Name of the fabric to perform config-save and/or deploy on",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"force_show_run": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "When true, fetch the latest running configuration from each switch instead of using the cached version before deployment.\n",
				MarkdownDescription: "When true, fetch the latest running configuration from each switch instead of using the cached version before deployment.\n",
				Default:             booldefault.StaticBool(false),
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "The unique identifier of the config_deploy resource",
				MarkdownDescription: "The unique identifier of the config_deploy resource",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"include_all_fabric_group_switches": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "When true and the target is a fabric group, deploy changes to switches in all member fabrics. Only applicable for fabric-wide deploy.\n",
				MarkdownDescription: "When true and the target is a fabric group, deploy changes to switches in all member fabrics. Only applicable for fabric-wide deploy.\n",
				Default:             booldefault.StaticBool(false),
			},
			"status": schema.StringAttribute{
				Computed:            true,
				Description:         "Status message from the last config-save or deploy operation. Read-only, populated by NDFC after the operation completes.\n",
				MarkdownDescription: "Status message from the last config-save or deploy operation. Read-only, populated by NDFC after the operation completes.\n",
			},
			"switch_ids": schema.SetAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Description:         "List of switch serial numbers or IP addresses to deploy configuration to. Use `[\"ALL\"]` to deploy to all switches in the fabric. When omitted, a fabric-wide deploy is performed. Note: IP address support is TBD\n",
				MarkdownDescription: "List of switch serial numbers or IP addresses to deploy configuration to. Use `[\"ALL\"]` to deploy to all switches in the fabric. When omitted, a fabric-wide deploy is performed. Note: IP address support is TBD\n",
			},
			"ticket_id": schema.StringAttribute{
				Optional:            true,
				Description:         "Change Control ticket ID to associate with the config-save operation. Must begin with a letter; remaining characters may be letters, numbers, underscores, or hyphens. Length: 1–64 characters.\n",
				MarkdownDescription: "Change Control ticket ID to associate with the config-save operation. Must begin with a letter; remaining characters may be letters, numbers, underscores, or hyphens. Length: 1–64 characters.\n",
			},
		},
		Description:         "Triggers fabric configuration save (recalculate) and/or deployment operations on an ND-managed fabric. This is an action resource — it executes config-save and deploy operations rather than managing a persistent API object.\n",
		MarkdownDescription: "Triggers fabric configuration save (recalculate) and/or deployment operations on an ND-managed fabric. This is an action resource — it executes config-save and deploy operations rather than managing a persistent API object.\n",
	}
}

type ConfigDeployModel struct {
	AlwaysDeploy                  types.Bool     `tfsdk:"always_deploy"`
	Behaviour                     BehaviourValue `tfsdk:"behaviour"`
	ConfigSave                    types.Bool     `tfsdk:"config_save"`
	Deploy                        types.Bool     `tfsdk:"deploy"`
	FabricName                    types.String   `tfsdk:"fabric_name"`
	ForceShowRun                  types.Bool     `tfsdk:"force_show_run"`
	Id                            types.String   `tfsdk:"id"`
	IncludeAllFabricGroupSwitches types.Bool     `tfsdk:"include_all_fabric_group_switches"`
	Status                        types.String   `tfsdk:"status"`
	SwitchIds                     types.Set      `tfsdk:"switch_ids"`
	TicketId                      types.String   `tfsdk:"ticket_id"`
}

var _ basetypes.ObjectTypable = BehaviourType{}

type BehaviourType struct {
	basetypes.ObjectType
}

func (t BehaviourType) Equal(o attr.Type) bool {
	other, ok := o.(BehaviourType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t BehaviourType) String() string {
	return "BehaviourType"
}

func (t BehaviourType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	deployOnCreateAttribute, ok := attributes["deploy_on_create"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`deploy_on_create is missing from object`)

		return nil, diags
	}

	deployOnCreateVal, ok := deployOnCreateAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`deploy_on_create expected to be basetypes.BoolValue, was: %T`, deployOnCreateAttribute))
	}

	deployOnDestroyAttribute, ok := attributes["deploy_on_destroy"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`deploy_on_destroy is missing from object`)

		return nil, diags
	}

	deployOnDestroyVal, ok := deployOnDestroyAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`deploy_on_destroy expected to be basetypes.BoolValue, was: %T`, deployOnDestroyAttribute))
	}

	deployOnUpdateAttribute, ok := attributes["deploy_on_update"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`deploy_on_update is missing from object`)

		return nil, diags
	}

	deployOnUpdateVal, ok := deployOnUpdateAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`deploy_on_update expected to be basetypes.BoolValue, was: %T`, deployOnUpdateAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return BehaviourValue{
		DeployOnCreate:  deployOnCreateVal,
		DeployOnDestroy: deployOnDestroyVal,
		DeployOnUpdate:  deployOnUpdateVal,
		state:           attr.ValueStateKnown,
	}, diags
}

func NewBehaviourValueNull() BehaviourValue {
	return BehaviourValue{
		state: attr.ValueStateNull,
	}
}

func NewBehaviourValueUnknown() BehaviourValue {
	return BehaviourValue{
		state: attr.ValueStateUnknown,
	}
}

func NewBehaviourValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (BehaviourValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing BehaviourValue Attribute Value",
				"While creating a BehaviourValue value, a missing attribute value was detected. "+
					"A BehaviourValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("BehaviourValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid BehaviourValue Attribute Type",
				"While creating a BehaviourValue value, an invalid attribute value was detected. "+
					"A BehaviourValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("BehaviourValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("BehaviourValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra BehaviourValue Attribute Value",
				"While creating a BehaviourValue value, an extra attribute value was detected. "+
					"A BehaviourValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra BehaviourValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewBehaviourValueUnknown(), diags
	}

	deployOnCreateAttribute, ok := attributes["deploy_on_create"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`deploy_on_create is missing from object`)

		return NewBehaviourValueUnknown(), diags
	}

	deployOnCreateVal, ok := deployOnCreateAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`deploy_on_create expected to be basetypes.BoolValue, was: %T`, deployOnCreateAttribute))
	}

	deployOnDestroyAttribute, ok := attributes["deploy_on_destroy"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`deploy_on_destroy is missing from object`)

		return NewBehaviourValueUnknown(), diags
	}

	deployOnDestroyVal, ok := deployOnDestroyAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`deploy_on_destroy expected to be basetypes.BoolValue, was: %T`, deployOnDestroyAttribute))
	}

	deployOnUpdateAttribute, ok := attributes["deploy_on_update"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`deploy_on_update is missing from object`)

		return NewBehaviourValueUnknown(), diags
	}

	deployOnUpdateVal, ok := deployOnUpdateAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`deploy_on_update expected to be basetypes.BoolValue, was: %T`, deployOnUpdateAttribute))
	}

	if diags.HasError() {
		return NewBehaviourValueUnknown(), diags
	}

	return BehaviourValue{
		DeployOnCreate:  deployOnCreateVal,
		DeployOnDestroy: deployOnDestroyVal,
		DeployOnUpdate:  deployOnUpdateVal,
		state:           attr.ValueStateKnown,
	}, diags
}

func NewBehaviourValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) BehaviourValue {
	object, diags := NewBehaviourValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewBehaviourValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t BehaviourType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewBehaviourValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewBehaviourValueUnknown(), nil
	}

	if in.IsNull() {
		return NewBehaviourValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewBehaviourValueMust(BehaviourValue{}.AttributeTypes(ctx), attributes), nil
}

func (t BehaviourType) ValueType(ctx context.Context) attr.Value {
	return BehaviourValue{}
}

var _ basetypes.ObjectValuable = BehaviourValue{}

type BehaviourValue struct {
	DeployOnCreate  basetypes.BoolValue `tfsdk:"deploy_on_create"`
	DeployOnDestroy basetypes.BoolValue `tfsdk:"deploy_on_destroy"`
	DeployOnUpdate  basetypes.BoolValue `tfsdk:"deploy_on_update"`
	state           attr.ValueState
}

func (v BehaviourValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 3)

	var val tftypes.Value
	var err error

	attrTypes["deploy_on_create"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["deploy_on_destroy"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["deploy_on_update"] = basetypes.BoolType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 3)

		val, err = v.DeployOnCreate.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["deploy_on_create"] = val

		val, err = v.DeployOnDestroy.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["deploy_on_destroy"] = val

		val, err = v.DeployOnUpdate.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["deploy_on_update"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v BehaviourValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v BehaviourValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v BehaviourValue) String() string {
	return "BehaviourValue"
}

func (v BehaviourValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"deploy_on_create":  basetypes.BoolType{},
		"deploy_on_destroy": basetypes.BoolType{},
		"deploy_on_update":  basetypes.BoolType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"deploy_on_create":  v.DeployOnCreate,
			"deploy_on_destroy": v.DeployOnDestroy,
			"deploy_on_update":  v.DeployOnUpdate,
		})

	return objVal, diags
}

func (v BehaviourValue) Equal(o attr.Value) bool {
	other, ok := o.(BehaviourValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.DeployOnCreate.Equal(other.DeployOnCreate) {
		return false
	}

	if !v.DeployOnDestroy.Equal(other.DeployOnDestroy) {
		return false
	}

	if !v.DeployOnUpdate.Equal(other.DeployOnUpdate) {
		return false
	}

	return true
}

func (v BehaviourValue) Type(ctx context.Context) attr.Type {
	return BehaviourType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v BehaviourValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"deploy_on_create":  basetypes.BoolType{},
		"deploy_on_destroy": basetypes.BoolType{},
		"deploy_on_update":  basetypes.BoolType{},
	}
}
