// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_inventory_switch

import (
	"context"
	"fmt"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64default"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func InventorySwitchResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"deploy": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Deploy configuration to switches after operations",
				MarkdownDescription: "Deploy configuration to switches after operations",
				Default:             booldefault.StaticBool(false),
			},
			"fabric_name": schema.StringAttribute{
				Required:            true,
				Description:         "Name of the fabric to add switches to",
				MarkdownDescription: "Name of the fabric to add switches to",
			},
			"max_hop": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Maximum hops for CDP/LLDP discovery",
				MarkdownDescription: "Maximum hops for CDP/LLDP discovery",
				Default:             int64default.StaticInt64(0),
			},
			"mode": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Operation mode - discovery (brownfield/greenfield) or bootstrap (POAP)",
				MarkdownDescription: "Operation mode - discovery (brownfield/greenfield) or bootstrap (POAP)",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
				Default: stringdefault.StaticString("discovery"),
			},
			"password": schema.StringAttribute{
				Optional:            true,
				Sensitive:           true,
				Description:         "Switch login password",
				MarkdownDescription: "Switch login password",
			},
			"platform_type": schema.StringAttribute{
				Computed:            true,
				Description:         "Platform type (nx-os, ios-xe)",
				MarkdownDescription: "Platform type (nx-os, ios-xe)",
			},
			"preserve_config": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Preserve existing config (true=brownfield, false=greenfield)",
				MarkdownDescription: "Preserve existing config (true=brownfield, false=greenfield)",
				Default:             booldefault.StaticBool(false),
			},
			"recalculate": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Recalculate (config-save) fabric configuration after switch operations",
				MarkdownDescription: "Recalculate (config-save) fabric configuration after switch operations",
				Default:             booldefault.StaticBool(false),
			},
			"remote_credential_store": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Credential store type (local, cyberark)",
				MarkdownDescription: "Credential store type (local, cyberark)",
				Default:             stringdefault.StaticString("local"),
			},
			"remote_credential_store_key": schema.StringAttribute{
				Optional:            true,
				Description:         "Key for remote credential store",
				MarkdownDescription: "Key for remote credential store",
			},
			"snmp_v3_auth_protocol": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "SNMP v3 authentication protocol",
				MarkdownDescription: "SNMP v3 authentication protocol",
				Default:             stringdefault.StaticString("MD5"),
			},
			"switches": schema.MapNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"discovery_auth_protocol": schema.StringAttribute{
							Optional:            true,
							Description:         "Authentication protocol for POAP discovery",
							MarkdownDescription: "Authentication protocol for POAP discovery",
						},
						"gateway_ip_mask": schema.StringAttribute{
							Optional:            true,
							Description:         "Gateway IP with mask for POAP (e.g., 10.1.1.1/24)",
							MarkdownDescription: "Gateway IP with mask for POAP (e.g., 10.1.1.1/24)",
						},
						"hostname": schema.StringAttribute{
							Computed:            true,
							Description:         "Switch hostname",
							MarkdownDescription: "Switch hostname",
							PlanModifiers: []planmodifier.String{
								stringplanmodifier.UseStateForUnknown(),
							},
						},
						"ip_address": schema.StringAttribute{
							Required:            true,
							Description:         "Switch management IP address",
							MarkdownDescription: "Switch management IP address",
						},
						"model": schema.StringAttribute{
							Optional:            true,
							Computed:            true,
							Description:         "Switch hardware model",
							MarkdownDescription: "Switch hardware model",
						},
						"poap_password": schema.StringAttribute{
							Optional:            true,
							Sensitive:           true,
							Description:         "Password for POAP bootstrap",
							MarkdownDescription: "Password for POAP bootstrap",
						},
						"serial_number": schema.StringAttribute{
							Computed:            true,
							Description:         "Switch serial number",
							MarkdownDescription: "Switch serial number",
							PlanModifiers: []planmodifier.String{
								stringplanmodifier.UseStateForUnknown(),
							},
						},
						"software_version": schema.StringAttribute{
							Optional:            true,
							Computed:            true,
							Description:         "Switch software version",
							MarkdownDescription: "Switch software version",
						},
						"status": schema.StringAttribute{
							Computed:            true,
							Description:         "Current switch status",
							MarkdownDescription: "Current switch status",
						},
						"status_reason": schema.StringAttribute{
							Computed:            true,
							Description:         "Reason for current switch status (e.g., failure details)",
							MarkdownDescription: "Reason for current switch status (e.g., failure details)",
						},
						"switch_role": schema.StringAttribute{
							Optional:            true,
							Computed:            true,
							Description:         "Role of switch in fabric.",
							MarkdownDescription: "Role of switch in fabric.",
							Default:             stringdefault.StaticString("leaf"),
						},
						"vdc_id": schema.Int64Attribute{
							Optional:            true,
							Computed:            true,
							Description:         "VDC ID for N7K switches",
							MarkdownDescription: "VDC ID for N7K switches",
						},
						"vdc_mac": schema.StringAttribute{
							Optional:            true,
							Computed:            true,
							Description:         "VDC MAC for N7K switches",
							MarkdownDescription: "VDC MAC for N7K switches",
						},
					},
					CustomType: SwitchesType{
						ObjectType: types.ObjectType{
							AttrTypes: SwitchesValue{}.AttributeTypes(ctx),
						},
					},
				},
				Required:            true,
				Description:         "Map of switches to manage, keyed by serial number",
				MarkdownDescription: "Map of switches to manage, keyed by serial number",
			},
			"username": schema.StringAttribute{
				Optional:            true,
				Sensitive:           true,
				Description:         "Switch login username",
				MarkdownDescription: "Switch login username",
			},
		},
	}
}

type InventorySwitchModel struct {
	Deploy                   types.Bool   `tfsdk:"deploy"`
	FabricName               types.String `tfsdk:"fabric_name"`
	MaxHop                   types.Int64  `tfsdk:"max_hop"`
	Mode                     types.String `tfsdk:"mode"`
	Password                 types.String `tfsdk:"password"`
	PlatformType             types.String `tfsdk:"platform_type"`
	PreserveConfig           types.Bool   `tfsdk:"preserve_config"`
	Recalculate              types.Bool   `tfsdk:"recalculate"`
	RemoteCredentialStore    types.String `tfsdk:"remote_credential_store"`
	RemoteCredentialStoreKey types.String `tfsdk:"remote_credential_store_key"`
	SnmpV3AuthProtocol       types.String `tfsdk:"snmp_v3_auth_protocol"`
	Switches                 types.Map    `tfsdk:"switches"`
	Username                 types.String `tfsdk:"username"`
}

var _ basetypes.ObjectTypable = SwitchesType{}

type SwitchesType struct {
	basetypes.ObjectType
}

func (t SwitchesType) Equal(o attr.Type) bool {
	other, ok := o.(SwitchesType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t SwitchesType) String() string {
	return "SwitchesType"
}

func (t SwitchesType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	discoveryAuthProtocolAttribute, ok := attributes["discovery_auth_protocol"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`discovery_auth_protocol is missing from object`)

		return nil, diags
	}

	discoveryAuthProtocolVal, ok := discoveryAuthProtocolAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`discovery_auth_protocol expected to be basetypes.StringValue, was: %T`, discoveryAuthProtocolAttribute))
	}

	gatewayIpMaskAttribute, ok := attributes["gateway_ip_mask"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`gateway_ip_mask is missing from object`)

		return nil, diags
	}

	gatewayIpMaskVal, ok := gatewayIpMaskAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`gateway_ip_mask expected to be basetypes.StringValue, was: %T`, gatewayIpMaskAttribute))
	}

	hostnameAttribute, ok := attributes["hostname"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`hostname is missing from object`)

		return nil, diags
	}

	hostnameVal, ok := hostnameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`hostname expected to be basetypes.StringValue, was: %T`, hostnameAttribute))
	}

	ipAddressAttribute, ok := attributes["ip_address"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ip_address is missing from object`)

		return nil, diags
	}

	ipAddressVal, ok := ipAddressAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ip_address expected to be basetypes.StringValue, was: %T`, ipAddressAttribute))
	}

	modelAttribute, ok := attributes["model"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`model is missing from object`)

		return nil, diags
	}

	modelVal, ok := modelAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`model expected to be basetypes.StringValue, was: %T`, modelAttribute))
	}

	poapPasswordAttribute, ok := attributes["poap_password"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`poap_password is missing from object`)

		return nil, diags
	}

	poapPasswordVal, ok := poapPasswordAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`poap_password expected to be basetypes.StringValue, was: %T`, poapPasswordAttribute))
	}

	serialNumberAttribute, ok := attributes["serial_number"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`serial_number is missing from object`)

		return nil, diags
	}

	serialNumberVal, ok := serialNumberAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`serial_number expected to be basetypes.StringValue, was: %T`, serialNumberAttribute))
	}

	softwareVersionAttribute, ok := attributes["software_version"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`software_version is missing from object`)

		return nil, diags
	}

	softwareVersionVal, ok := softwareVersionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`software_version expected to be basetypes.StringValue, was: %T`, softwareVersionAttribute))
	}

	statusAttribute, ok := attributes["status"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`status is missing from object`)

		return nil, diags
	}

	statusVal, ok := statusAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`status expected to be basetypes.StringValue, was: %T`, statusAttribute))
	}

	statusReasonAttribute, ok := attributes["status_reason"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`status_reason is missing from object`)

		return nil, diags
	}

	statusReasonVal, ok := statusReasonAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`status_reason expected to be basetypes.StringValue, was: %T`, statusReasonAttribute))
	}

	switchRoleAttribute, ok := attributes["switch_role"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`switch_role is missing from object`)

		return nil, diags
	}

	switchRoleVal, ok := switchRoleAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`switch_role expected to be basetypes.StringValue, was: %T`, switchRoleAttribute))
	}

	vdcIdAttribute, ok := attributes["vdc_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`vdc_id is missing from object`)

		return nil, diags
	}

	vdcIdVal, ok := vdcIdAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`vdc_id expected to be basetypes.Int64Value, was: %T`, vdcIdAttribute))
	}

	vdcMacAttribute, ok := attributes["vdc_mac"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`vdc_mac is missing from object`)

		return nil, diags
	}

	vdcMacVal, ok := vdcMacAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`vdc_mac expected to be basetypes.StringValue, was: %T`, vdcMacAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return SwitchesValue{
		DiscoveryAuthProtocol: discoveryAuthProtocolVal,
		GatewayIpMask:         gatewayIpMaskVal,
		Hostname:              hostnameVal,
		IpAddress:             ipAddressVal,
		Model:                 modelVal,
		PoapPassword:          poapPasswordVal,
		SerialNumber:          serialNumberVal,
		SoftwareVersion:       softwareVersionVal,
		Status:                statusVal,
		StatusReason:          statusReasonVal,
		SwitchRole:            switchRoleVal,
		VdcId:                 vdcIdVal,
		VdcMac:                vdcMacVal,
		state:                 attr.ValueStateKnown,
	}, diags
}

func NewSwitchesValueNull() SwitchesValue {
	return SwitchesValue{
		state: attr.ValueStateNull,
	}
}

func NewSwitchesValueUnknown() SwitchesValue {
	return SwitchesValue{
		state: attr.ValueStateUnknown,
	}
}

func NewSwitchesValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (SwitchesValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing SwitchesValue Attribute Value",
				"While creating a SwitchesValue value, a missing attribute value was detected. "+
					"A SwitchesValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("SwitchesValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid SwitchesValue Attribute Type",
				"While creating a SwitchesValue value, an invalid attribute value was detected. "+
					"A SwitchesValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("SwitchesValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("SwitchesValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra SwitchesValue Attribute Value",
				"While creating a SwitchesValue value, an extra attribute value was detected. "+
					"A SwitchesValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra SwitchesValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewSwitchesValueUnknown(), diags
	}

	discoveryAuthProtocolAttribute, ok := attributes["discovery_auth_protocol"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`discovery_auth_protocol is missing from object`)

		return NewSwitchesValueUnknown(), diags
	}

	discoveryAuthProtocolVal, ok := discoveryAuthProtocolAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`discovery_auth_protocol expected to be basetypes.StringValue, was: %T`, discoveryAuthProtocolAttribute))
	}

	gatewayIpMaskAttribute, ok := attributes["gateway_ip_mask"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`gateway_ip_mask is missing from object`)

		return NewSwitchesValueUnknown(), diags
	}

	gatewayIpMaskVal, ok := gatewayIpMaskAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`gateway_ip_mask expected to be basetypes.StringValue, was: %T`, gatewayIpMaskAttribute))
	}

	hostnameAttribute, ok := attributes["hostname"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`hostname is missing from object`)

		return NewSwitchesValueUnknown(), diags
	}

	hostnameVal, ok := hostnameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`hostname expected to be basetypes.StringValue, was: %T`, hostnameAttribute))
	}

	ipAddressAttribute, ok := attributes["ip_address"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ip_address is missing from object`)

		return NewSwitchesValueUnknown(), diags
	}

	ipAddressVal, ok := ipAddressAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ip_address expected to be basetypes.StringValue, was: %T`, ipAddressAttribute))
	}

	modelAttribute, ok := attributes["model"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`model is missing from object`)

		return NewSwitchesValueUnknown(), diags
	}

	modelVal, ok := modelAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`model expected to be basetypes.StringValue, was: %T`, modelAttribute))
	}

	poapPasswordAttribute, ok := attributes["poap_password"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`poap_password is missing from object`)

		return NewSwitchesValueUnknown(), diags
	}

	poapPasswordVal, ok := poapPasswordAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`poap_password expected to be basetypes.StringValue, was: %T`, poapPasswordAttribute))
	}

	serialNumberAttribute, ok := attributes["serial_number"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`serial_number is missing from object`)

		return NewSwitchesValueUnknown(), diags
	}

	serialNumberVal, ok := serialNumberAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`serial_number expected to be basetypes.StringValue, was: %T`, serialNumberAttribute))
	}

	softwareVersionAttribute, ok := attributes["software_version"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`software_version is missing from object`)

		return NewSwitchesValueUnknown(), diags
	}

	softwareVersionVal, ok := softwareVersionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`software_version expected to be basetypes.StringValue, was: %T`, softwareVersionAttribute))
	}

	statusAttribute, ok := attributes["status"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`status is missing from object`)

		return NewSwitchesValueUnknown(), diags
	}

	statusVal, ok := statusAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`status expected to be basetypes.StringValue, was: %T`, statusAttribute))
	}

	statusReasonAttribute, ok := attributes["status_reason"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`status_reason is missing from object`)

		return NewSwitchesValueUnknown(), diags
	}

	statusReasonVal, ok := statusReasonAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`status_reason expected to be basetypes.StringValue, was: %T`, statusReasonAttribute))
	}

	switchRoleAttribute, ok := attributes["switch_role"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`switch_role is missing from object`)

		return NewSwitchesValueUnknown(), diags
	}

	switchRoleVal, ok := switchRoleAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`switch_role expected to be basetypes.StringValue, was: %T`, switchRoleAttribute))
	}

	vdcIdAttribute, ok := attributes["vdc_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`vdc_id is missing from object`)

		return NewSwitchesValueUnknown(), diags
	}

	vdcIdVal, ok := vdcIdAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`vdc_id expected to be basetypes.Int64Value, was: %T`, vdcIdAttribute))
	}

	vdcMacAttribute, ok := attributes["vdc_mac"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`vdc_mac is missing from object`)

		return NewSwitchesValueUnknown(), diags
	}

	vdcMacVal, ok := vdcMacAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`vdc_mac expected to be basetypes.StringValue, was: %T`, vdcMacAttribute))
	}

	if diags.HasError() {
		return NewSwitchesValueUnknown(), diags
	}

	return SwitchesValue{
		DiscoveryAuthProtocol: discoveryAuthProtocolVal,
		GatewayIpMask:         gatewayIpMaskVal,
		Hostname:              hostnameVal,
		IpAddress:             ipAddressVal,
		Model:                 modelVal,
		PoapPassword:          poapPasswordVal,
		SerialNumber:          serialNumberVal,
		SoftwareVersion:       softwareVersionVal,
		Status:                statusVal,
		StatusReason:          statusReasonVal,
		SwitchRole:            switchRoleVal,
		VdcId:                 vdcIdVal,
		VdcMac:                vdcMacVal,
		state:                 attr.ValueStateKnown,
	}, diags
}

func NewSwitchesValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) SwitchesValue {
	object, diags := NewSwitchesValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewSwitchesValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t SwitchesType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewSwitchesValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewSwitchesValueUnknown(), nil
	}

	if in.IsNull() {
		return NewSwitchesValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewSwitchesValueMust(SwitchesValue{}.AttributeTypes(ctx), attributes), nil
}

func (t SwitchesType) ValueType(ctx context.Context) attr.Value {
	return SwitchesValue{}
}

var _ basetypes.ObjectValuable = SwitchesValue{}

type SwitchesValue struct {
	DiscoveryAuthProtocol basetypes.StringValue `tfsdk:"discovery_auth_protocol"`
	GatewayIpMask         basetypes.StringValue `tfsdk:"gateway_ip_mask"`
	Hostname              basetypes.StringValue `tfsdk:"hostname"`
	IpAddress             basetypes.StringValue `tfsdk:"ip_address"`
	Model                 basetypes.StringValue `tfsdk:"model"`
	PoapPassword          basetypes.StringValue `tfsdk:"poap_password"`
	SerialNumber          basetypes.StringValue `tfsdk:"serial_number"`
	SoftwareVersion       basetypes.StringValue `tfsdk:"software_version"`
	Status                basetypes.StringValue `tfsdk:"status"`
	StatusReason          basetypes.StringValue `tfsdk:"status_reason"`
	SwitchRole            basetypes.StringValue `tfsdk:"switch_role"`
	VdcId                 basetypes.Int64Value  `tfsdk:"vdc_id"`
	VdcMac                basetypes.StringValue `tfsdk:"vdc_mac"`
	state                 attr.ValueState
}

func (v SwitchesValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 13)

	var val tftypes.Value
	var err error

	attrTypes["discovery_auth_protocol"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["gateway_ip_mask"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["hostname"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["ip_address"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["model"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["poap_password"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["serial_number"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["software_version"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["status"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["status_reason"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["switch_role"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["vdc_id"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["vdc_mac"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 13)

		val, err = v.DiscoveryAuthProtocol.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["discovery_auth_protocol"] = val

		val, err = v.GatewayIpMask.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["gateway_ip_mask"] = val

		val, err = v.Hostname.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["hostname"] = val

		val, err = v.IpAddress.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["ip_address"] = val

		val, err = v.Model.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["model"] = val

		val, err = v.PoapPassword.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["poap_password"] = val

		val, err = v.SerialNumber.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["serial_number"] = val

		val, err = v.SoftwareVersion.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["software_version"] = val

		val, err = v.Status.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["status"] = val

		val, err = v.StatusReason.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["status_reason"] = val

		val, err = v.SwitchRole.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["switch_role"] = val

		val, err = v.VdcId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["vdc_id"] = val

		val, err = v.VdcMac.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["vdc_mac"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v SwitchesValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v SwitchesValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v SwitchesValue) String() string {
	return "SwitchesValue"
}

func (v SwitchesValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"discovery_auth_protocol": basetypes.StringType{},
		"gateway_ip_mask":         basetypes.StringType{},
		"hostname":                basetypes.StringType{},
		"ip_address":              basetypes.StringType{},
		"model":                   basetypes.StringType{},
		"poap_password":           basetypes.StringType{},
		"serial_number":           basetypes.StringType{},
		"software_version":        basetypes.StringType{},
		"status":                  basetypes.StringType{},
		"status_reason":           basetypes.StringType{},
		"switch_role":             basetypes.StringType{},
		"vdc_id":                  basetypes.Int64Type{},
		"vdc_mac":                 basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"discovery_auth_protocol": v.DiscoveryAuthProtocol,
			"gateway_ip_mask":         v.GatewayIpMask,
			"hostname":                v.Hostname,
			"ip_address":              v.IpAddress,
			"model":                   v.Model,
			"poap_password":           v.PoapPassword,
			"serial_number":           v.SerialNumber,
			"software_version":        v.SoftwareVersion,
			"status":                  v.Status,
			"status_reason":           v.StatusReason,
			"switch_role":             v.SwitchRole,
			"vdc_id":                  v.VdcId,
			"vdc_mac":                 v.VdcMac,
		})

	return objVal, diags
}

func (v SwitchesValue) Equal(o attr.Value) bool {
	other, ok := o.(SwitchesValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.DiscoveryAuthProtocol.Equal(other.DiscoveryAuthProtocol) {
		return false
	}

	if !v.GatewayIpMask.Equal(other.GatewayIpMask) {
		return false
	}

	if !v.Hostname.Equal(other.Hostname) {
		return false
	}

	if !v.IpAddress.Equal(other.IpAddress) {
		return false
	}

	if !v.Model.Equal(other.Model) {
		return false
	}

	if !v.PoapPassword.Equal(other.PoapPassword) {
		return false
	}

	if !v.SerialNumber.Equal(other.SerialNumber) {
		return false
	}

	if !v.SoftwareVersion.Equal(other.SoftwareVersion) {
		return false
	}

	if !v.Status.Equal(other.Status) {
		return false
	}

	if !v.StatusReason.Equal(other.StatusReason) {
		return false
	}

	if !v.SwitchRole.Equal(other.SwitchRole) {
		return false
	}

	if !v.VdcId.Equal(other.VdcId) {
		return false
	}

	if !v.VdcMac.Equal(other.VdcMac) {
		return false
	}

	return true
}

func (v SwitchesValue) Type(ctx context.Context) attr.Type {
	return SwitchesType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v SwitchesValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"discovery_auth_protocol": basetypes.StringType{},
		"gateway_ip_mask":         basetypes.StringType{},
		"hostname":                basetypes.StringType{},
		"ip_address":              basetypes.StringType{},
		"model":                   basetypes.StringType{},
		"poap_password":           basetypes.StringType{},
		"serial_number":           basetypes.StringType{},
		"software_version":        basetypes.StringType{},
		"status":                  basetypes.StringType{},
		"status_reason":           basetypes.StringType{},
		"switch_role":             basetypes.StringType{},
		"vdc_id":                  basetypes.Int64Type{},
		"vdc_mac":                 basetypes.StringType{},
	}
}
