// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_tenant_domain

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func TenantDomainResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"description": schema.StringAttribute{
				Optional:            true,
				Description:         "The description of the tenant domain.",
				MarkdownDescription: "The description of the tenant domain.",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "The unique identifier for the resource, it is the name of the tenant domain (for example, tenant_domain1).",
				MarkdownDescription: "The unique identifier for the resource, it is the name of the tenant domain (for example, tenant_domain1).",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "The name of the tenant domain.",
				MarkdownDescription: "The name of the tenant domain.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"tenant_names": schema.SetAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Description:         "The complete list of tenants associated with the tenant domain.",
				MarkdownDescription: "The complete list of tenants associated with the tenant domain.",
			},
		},
		Description:         "Manages tenant domain for Nexus Dashboard",
		MarkdownDescription: "Manages tenant domain for Nexus Dashboard",
	}
}

type TenantDomainModel struct {
	Description types.String `tfsdk:"description"`
	Id          types.String `tfsdk:"id"`
	Name        types.String `tfsdk:"name"`
	TenantNames types.Set    `tfsdk:"tenant_names"`
}
