// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_tenant_domain

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func TenantDomainDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"description": schema.StringAttribute{
				Computed:            true,
				Description:         "The description of the tenant domain.",
				MarkdownDescription: "The description of the tenant domain.",
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "The name that uniquely identifies the tenant domain datasource.",
				MarkdownDescription: "The name that uniquely identifies the tenant domain datasource.",
				Validators: []validator.String{
					stringvalidator.LengthBetween(1, 63),
				},
			},
			"tenant_names": schema.SetAttribute{
				ElementType:         types.StringType,
				Computed:            true,
				Description:         "The complete list of tenants associated with the tenant domain.",
				MarkdownDescription: "The complete list of tenants associated with the tenant domain.",
			},
		},
		Description:         "Datasource of the tenant domain for Nexus Dashboard",
		MarkdownDescription: "Datasource of the tenant domain for Nexus Dashboard",
	}
}

type TenantDomainModel struct {
	Description types.String `tfsdk:"description"`
	Name        types.String `tfsdk:"name"`
	TenantNames types.Set    `tfsdk:"tenant_names"`
}
