// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_tenant

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func TenantResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"description": schema.StringAttribute{
				Optional:            true,
				Description:         "The description of the tenant.",
				MarkdownDescription: "The description of the tenant.",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "The unique identifier of the terraform resource.",
				MarkdownDescription: "The unique identifier of the terraform resource.",
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "The name of the tenant.",
				MarkdownDescription: "The name of the tenant.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
		},
	}
}

type TenantModel struct {
	Description types.String `tfsdk:"description"`
	Id          types.String `tfsdk:"id"`
	Name        types.String `tfsdk:"name"`
}
