// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_backup

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"regexp"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func BackupResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"destination": schema.StringAttribute{
				Required:            true,
				Description:         "The name of the remote location where the backup file will be saved. An empty string indicates a Nexus Dashboard local backup.",
				MarkdownDescription: "The name of the remote location where the backup file will be saved. An empty string indicates a Nexus Dashboard local backup.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"encryption_key": schema.StringAttribute{
				Required:            true,
				Sensitive:           true,
				Description:         "The encryption key used to encrypt the backup file. Must be at least 8 characters long and contain at least one letter and one number.",
				MarkdownDescription: "The encryption key used to encrypt the backup file. Must be at least 8 characters long and contain at least one letter and one number.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
				Validators: []validator.String{
					stringvalidator.LengthBetween(8, 256),
				},
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "The name of the backup. Start with a lowercase letter or digit (a-z, 0-9), end with a lowercase letter or digit, may contain lowercase letters, digits, or hyphens in between, and must be at least 1 character long (a single letter/digit is OK).",
				MarkdownDescription: "The name of the backup. Start with a lowercase letter or digit (a-z, 0-9), end with a lowercase letter or digit, may contain lowercase letters, digits, or hyphens in between, and must be at least 1 character long (a single letter/digit is OK).",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
				Validators: []validator.String{
					stringvalidator.LengthBetween(1, 63), stringvalidator.RegexMatches(regexp.MustCompile(`^[a-z0-9]([a-z0-9-]*[a-z0-9])?(\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)*$`), "must start and end with an alphanumeric character and may contain lowercase letters, digits, hyphens, and dots"),
				},
			},
			"telemetry_data": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "When set to true, telemetry operational data will be collected. Telemetry operational data can only be collected when `type` is `full` and `destination` is a NAS remote storage location.",
				MarkdownDescription: "When set to true, telemetry operational data will be collected. Telemetry operational data can only be collected when `type` is `full` and `destination` is a NAS remote storage location.",
				PlanModifiers: []planmodifier.Bool{
					boolplanmodifier.UseStateForUnknown(),
				},
			},
			"type": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The type of the backup. `configOnly` backs up the system configuration only, while `full` backs up the system configuration and operational data.",
				MarkdownDescription: "The type of the backup. `configOnly` backs up the system configuration only, while `full` backs up the system configuration and operational data.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
					stringplanmodifier.UseStateForUnknown(),
				},
				Default: stringdefault.StaticString("configOnly"),
			},
		},
	}
}

type BackupModel struct {
	Destination   types.String `tfsdk:"destination"`
	EncryptionKey types.String `tfsdk:"encryption_key"`
	Name          types.String `tfsdk:"name"`
	TelemetryData types.Bool   `tfsdk:"telemetry_data"`
	Type          types.String `tfsdk:"type"`
}
