// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_multi_cluster_connectivity

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func MultiClusterConnectivityResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"cluster_name": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The name of the ND cluster.",
				MarkdownDescription: "The name of the ND cluster.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"cluster_type": schema.StringAttribute{
				Computed:            true,
				Description:         "The type of the cluster. The value will be auto filled as \"ND\" for this resource.",
				MarkdownDescription: "The type of the cluster. The value will be auto filled as \"ND\" for this resource.",
			},
			"hostname": schema.StringAttribute{
				Required:            true,
				Description:         "The IP address or Hostname of the ND cluster.",
				MarkdownDescription: "The IP address or Hostname of the ND cluster.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"login_domain": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Sensitive:           true,
				Description:         "The login domain of the ND cluster. The login domain is used during the connection of clusters to specify the authentication domain for the remote clusters.",
				MarkdownDescription: "The login domain of the ND cluster. The login domain is used during the connection of clusters to specify the authentication domain for the remote clusters.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"multi_cluster_login_domain": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Sensitive:           true,
				Description:         "The multi-cluster login domain is created on the primary cluster and can be configured either during initial onboarding or manually at a later time. Each primary cluster supports only one login domain of type Multi-cluster. This domain enables the primary cluster to function as the shared authentication authority for the multi-cluster group, allowing users defined on the primary cluster to remotely log in to any connected cluster.",
				MarkdownDescription: "The multi-cluster login domain is created on the primary cluster and can be configured either during initial onboarding or manually at a later time. Each primary cluster supports only one login domain of type Multi-cluster. This domain enables the primary cluster to function as the shared authentication authority for the multi-cluster group, allowing users defined on the primary cluster to remotely log in to any connected cluster.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"password": schema.StringAttribute{
				Required:            true,
				Sensitive:           true,
				Description:         "The password of the ND cluster.",
				MarkdownDescription: "The password of the ND cluster.",
			},
			"username": schema.StringAttribute{
				Required:            true,
				Sensitive:           true,
				Description:         "The username of the ND cluster.",
				MarkdownDescription: "The username of the ND cluster.",
			},
		},
	}
}

type MultiClusterConnectivityModel struct {
	ClusterName             types.String `tfsdk:"cluster_name"`
	ClusterType             types.String `tfsdk:"cluster_type"`
	Hostname                types.String `tfsdk:"hostname"`
	LoginDomain             types.String `tfsdk:"login_domain"`
	MultiClusterLoginDomain types.String `tfsdk:"multi_cluster_login_domain"`
	Password                types.String `tfsdk:"password"`
	Username                types.String `tfsdk:"username"`
}
