// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_local_user

import (
	"context"
	"fmt"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework-validators/setvalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func LocalUserResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"email": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The email address of the local user.",
				MarkdownDescription: "The email address of the local user.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"first_name": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The first name of the local user.",
				MarkdownDescription: "The first name of the local user.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"last_name": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The last name of the local user.",
				MarkdownDescription: "The last name of the local user.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"login_id": schema.StringAttribute{
				Required:            true,
				Description:         "The login ID of the local user.",
				MarkdownDescription: "The login ID of the local user.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"remote_id_claim": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The CX UserID mapped to the local user.",
				MarkdownDescription: "The CX UserID mapped to the local user.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"remote_user_authorization": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The user cross launch option of the local user.",
				MarkdownDescription: "The user cross launch option of the local user.",
				PlanModifiers: []planmodifier.Bool{
					boolplanmodifier.UseStateForUnknown(),
				},
				Default: booldefault.StaticBool(false),
			},
			"reuse_limitation": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "The password reuse limitation of the local user.",
				MarkdownDescription: "The password reuse limitation of the local user.",
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.UseStateForUnknown(),
				},
			},
			"security_domains": schema.MapNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"roles": schema.SetAttribute{
							ElementType:         types.StringType,
							Required:            true,
							Description:         "The list of Nexus Dashboard Roles of the local user. Allowed values are \"approver\", \"designer\", \"fabric-admin\", \"observer\", \"super-admin\", and \"support-engineer\".",
							MarkdownDescription: "The list of Nexus Dashboard Roles of the local user. Allowed values are \"approver\", \"designer\", \"fabric-admin\", \"observer\", \"super-admin\", and \"support-engineer\".",
							Validators: []validator.Set{
								setvalidator.ValueStringsAre(stringvalidator.OneOf("approver", "designer", "fabric-admin", "observer", "super-admin", "support-engineer")),
							},
						},
					},
					CustomType: SecurityDomainsType{
						ObjectType: types.ObjectType{
							AttrTypes: SecurityDomainsValue{}.AttributeTypes(ctx),
						},
					},
				},
				Required:            true,
				Description:         "The security domains of the local user. At least one security domain must be provided when creating the user.",
				MarkdownDescription: "The security domains of the local user. At least one security domain must be provided when creating the user.",
			},
			"tenant_domain": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The name of the tenant domain of the local user.",
				MarkdownDescription: "The name of the tenant domain of the local user.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"time_interval_limitation": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "The password time interval limitation of the local user.",
				MarkdownDescription: "The password time interval limitation of the local user.",
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.UseStateForUnknown(),
				},
			},
			"user_password": schema.StringAttribute{
				Required:            true,
				Sensitive:           true,
				Description:         "The password of the local user.",
				MarkdownDescription: "The password of the local user.",
			},
		},
	}
}

type LocalUserModel struct {
	Email                   types.String `tfsdk:"email"`
	FirstName               types.String `tfsdk:"first_name"`
	LastName                types.String `tfsdk:"last_name"`
	LoginId                 types.String `tfsdk:"login_id"`
	RemoteIdClaim           types.String `tfsdk:"remote_id_claim"`
	RemoteUserAuthorization types.Bool   `tfsdk:"remote_user_authorization"`
	ReuseLimitation         types.Int64  `tfsdk:"reuse_limitation"`
	SecurityDomains         types.Map    `tfsdk:"security_domains"`
	TenantDomain            types.String `tfsdk:"tenant_domain"`
	TimeIntervalLimitation  types.Int64  `tfsdk:"time_interval_limitation"`
	UserPassword            types.String `tfsdk:"user_password"`
}

var _ basetypes.ObjectTypable = SecurityDomainsType{}

type SecurityDomainsType struct {
	basetypes.ObjectType
}

func (t SecurityDomainsType) Equal(o attr.Type) bool {
	other, ok := o.(SecurityDomainsType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t SecurityDomainsType) String() string {
	return "SecurityDomainsType"
}

func (t SecurityDomainsType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	rolesAttribute, ok := attributes["roles"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`roles is missing from object`)

		return nil, diags
	}

	rolesVal, ok := rolesAttribute.(basetypes.SetValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`roles expected to be basetypes.SetValue, was: %T`, rolesAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return SecurityDomainsValue{
		Roles: rolesVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewSecurityDomainsValueNull() SecurityDomainsValue {
	return SecurityDomainsValue{
		state: attr.ValueStateNull,
	}
}

func NewSecurityDomainsValueUnknown() SecurityDomainsValue {
	return SecurityDomainsValue{
		state: attr.ValueStateUnknown,
	}
}

func NewSecurityDomainsValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (SecurityDomainsValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing SecurityDomainsValue Attribute Value",
				"While creating a SecurityDomainsValue value, a missing attribute value was detected. "+
					"A SecurityDomainsValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("SecurityDomainsValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid SecurityDomainsValue Attribute Type",
				"While creating a SecurityDomainsValue value, an invalid attribute value was detected. "+
					"A SecurityDomainsValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("SecurityDomainsValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("SecurityDomainsValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra SecurityDomainsValue Attribute Value",
				"While creating a SecurityDomainsValue value, an extra attribute value was detected. "+
					"A SecurityDomainsValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra SecurityDomainsValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewSecurityDomainsValueUnknown(), diags
	}

	rolesAttribute, ok := attributes["roles"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`roles is missing from object`)

		return NewSecurityDomainsValueUnknown(), diags
	}

	rolesVal, ok := rolesAttribute.(basetypes.SetValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`roles expected to be basetypes.SetValue, was: %T`, rolesAttribute))
	}

	if diags.HasError() {
		return NewSecurityDomainsValueUnknown(), diags
	}

	return SecurityDomainsValue{
		Roles: rolesVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewSecurityDomainsValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) SecurityDomainsValue {
	object, diags := NewSecurityDomainsValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewSecurityDomainsValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t SecurityDomainsType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewSecurityDomainsValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewSecurityDomainsValueUnknown(), nil
	}

	if in.IsNull() {
		return NewSecurityDomainsValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewSecurityDomainsValueMust(SecurityDomainsValue{}.AttributeTypes(ctx), attributes), nil
}

func (t SecurityDomainsType) ValueType(ctx context.Context) attr.Value {
	return SecurityDomainsValue{}
}

var _ basetypes.ObjectValuable = SecurityDomainsValue{}

type SecurityDomainsValue struct {
	Roles basetypes.SetValue `tfsdk:"roles"`
	state attr.ValueState
}

func (v SecurityDomainsValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 1)

	var val tftypes.Value
	var err error

	attrTypes["roles"] = basetypes.SetType{
		ElemType: types.StringType,
	}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 1)

		val, err = v.Roles.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["roles"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v SecurityDomainsValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v SecurityDomainsValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v SecurityDomainsValue) String() string {
	return "SecurityDomainsValue"
}

func (v SecurityDomainsValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var rolesVal basetypes.SetValue
	switch {
	case v.Roles.IsUnknown():
		rolesVal = types.SetUnknown(types.StringType)
	case v.Roles.IsNull():
		rolesVal = types.SetNull(types.StringType)
	default:
		var d diag.Diagnostics
		rolesVal, d = types.SetValue(types.StringType, v.Roles.Elements())
		diags.Append(d...)
	}

	if diags.HasError() {
		return types.ObjectUnknown(map[string]attr.Type{
			"roles": basetypes.SetType{
				ElemType: types.StringType,
			},
		}), diags
	}

	attributeTypes := map[string]attr.Type{
		"roles": basetypes.SetType{
			ElemType: types.StringType,
		},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"roles": rolesVal,
		})

	return objVal, diags
}

func (v SecurityDomainsValue) Equal(o attr.Value) bool {
	other, ok := o.(SecurityDomainsValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Roles.Equal(other.Roles) {
		return false
	}

	return true
}

func (v SecurityDomainsValue) Type(ctx context.Context) attr.Type {
	return SecurityDomainsType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v SecurityDomainsValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"roles": basetypes.SetType{
			ElemType: types.StringType,
		},
	}
}
