// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_multi_cluster_connectivity_nd

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func MultiClusterConnectivityNdResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"cluster_name": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The name of the ND cluster.",
				MarkdownDescription: "The name of the ND cluster.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"cluster_type": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The type of the cluster. The value will be auto filled as \"ND\" for this resource.",
				MarkdownDescription: "The type of the cluster. The value will be auto filled as \"ND\" for this resource.",
				Default:             stringdefault.StaticString("ND"),
			},
			"hostname": schema.StringAttribute{
				Required:            true,
				Description:         "The IP address or Hostname of the cluster.",
				MarkdownDescription: "The IP address or Hostname of the cluster.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "The unique identifier of the terraform resource.",
				MarkdownDescription: "The unique identifier of the terraform resource.",
			},
			"login_domain": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The login domain of the cluster.",
				MarkdownDescription: "The login domain of the cluster.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"multi_cluster_login_domain": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The multi cluster login domain of the cluster. The multi cluster login domain will be auto created when it is not present in the primary cluster.",
				MarkdownDescription: "The multi cluster login domain of the cluster. The multi cluster login domain will be auto created when it is not present in the primary cluster.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"password": schema.StringAttribute{
				Required:            true,
				Sensitive:           true,
				Description:         "The password of the cluster.",
				MarkdownDescription: "The password of the cluster.",
			},
			"username": schema.StringAttribute{
				Required:            true,
				Description:         "The username of the cluster.",
				MarkdownDescription: "The username of the cluster.",
			},
		},
	}
}

type MultiClusterConnectivityNdModel struct {
	ClusterName             types.String `tfsdk:"cluster_name"`
	ClusterType             types.String `tfsdk:"cluster_type"`
	Hostname                types.String `tfsdk:"hostname"`
	Id                      types.String `tfsdk:"id"`
	LoginDomain             types.String `tfsdk:"login_domain"`
	MultiClusterLoginDomain types.String `tfsdk:"multi_cluster_login_domain"`
	Password                types.String `tfsdk:"password"`
	Username                types.String `tfsdk:"username"`
}
