// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_vpc_pair

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func VpcPairResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"deploy": schema.BoolAttribute{
				Optional:            true,
				Description:         "Deploy vPC pair",
				MarkdownDescription: "Deploy vPC pair",
			},
			"fabric_name": schema.StringAttribute{
				Computed:            true,
				Description:         "Name of the fabric resolved from the switch inventory",
				MarkdownDescription: "Name of the fabric resolved from the switch inventory",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "The Terraform Unique Identifier for the vPC pair resource `<fabric_name>/<switch1_serial_number>:<switch2_serial_number>`",
				MarkdownDescription: "The Terraform Unique Identifier for the vPC pair resource `<fabric_name>/<switch1_serial_number>:<switch2_serial_number>`",
			},
			"switch_1_serial_number": schema.StringAttribute{
				Required:            true,
				Description:         "Serial number of the peer switch in the vPC pair.",
				MarkdownDescription: "Serial number of the peer switch in the vPC pair.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"switch_2_serial_number": schema.StringAttribute{
				Required:            true,
				Description:         "Serial number of the switch where the vPC pair is being configured.",
				MarkdownDescription: "Serial number of the switch where the vPC pair is being configured.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"use_virtual_peerlink": schema.BoolAttribute{
				Optional:            true,
				Description:         "Set to true to use virtual peer link",
				MarkdownDescription: "Set to true to use virtual peer link",
			},
		},
		Description:         "Resource to configure vPC pair on a switch. Note only VXLAN EVPN fabric is supported",
		MarkdownDescription: "Resource to configure vPC pair on a switch. Note only VXLAN EVPN fabric is supported",
	}
}

type VpcPairModel struct {
	Deploy              types.Bool   `tfsdk:"deploy"`
	FabricName          types.String `tfsdk:"fabric_name"`
	Id                  types.String `tfsdk:"id"`
	Switch1SerialNumber types.String `tfsdk:"switch_1_serial_number"`
	Switch2SerialNumber types.String `tfsdk:"switch_2_serial_number"`
	UseVirtualPeerlink  types.Bool   `tfsdk:"use_virtual_peerlink"`
}
