// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_change_control

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func ChangeControlDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"admin_status": schema.BoolAttribute{
				Computed:            true,
				Description:         "The admin status of the change control.",
				MarkdownDescription: "The admin status of the change control.",
			},
			"allow_self_approval": schema.BoolAttribute{
				Computed:            true,
				Description:         "The self approval status of the change control for an orchestration action to approve that ticket.",
				MarkdownDescription: "The self approval status of the change control for an orchestration action to approve that ticket.",
			},
			"bypass_telemetry_change_control": schema.BoolAttribute{
				Computed:            true,
				Description:         "Bypasses change control for telemetry operations in Nexus Dashboard managed fabrics.",
				MarkdownDescription: "Bypasses change control for telemetry operations in Nexus Dashboard managed fabrics.",
			},
			"nd_managed_fabrics": schema.BoolAttribute{
				Computed:            true,
				Description:         "The Nexus Dashboard managed fabrics status of the change control.",
				MarkdownDescription: "The Nexus Dashboard managed fabrics status of the change control.",
			},
			"number_of_approvers": schema.Int64Attribute{
				Computed:            true,
				Description:         "The number of approvals required for orchestration templates.",
				MarkdownDescription: "The number of approvals required for orchestration templates.",
			},
			"orchestration": schema.BoolAttribute{
				Computed:            true,
				Description:         "The orchestration status of the change control for ACI fabrics.",
				MarkdownDescription: "The orchestration status of the change control for ACI fabrics.",
			},
			"ticket_name_prefix": schema.StringAttribute{
				Computed:            true,
				Description:         "The prefix of the ticket name for the change control.",
				MarkdownDescription: "The prefix of the ticket name for the change control.",
			},
		},
		Description:         "Datasource of the change control system settings for Nexus Dashboard",
		MarkdownDescription: "Datasource of the change control system settings for Nexus Dashboard",
	}
}

type ChangeControlModel struct {
	AdminStatus                  types.Bool   `tfsdk:"admin_status"`
	AllowSelfApproval            types.Bool   `tfsdk:"allow_self_approval"`
	BypassTelemetryChangeControl types.Bool   `tfsdk:"bypass_telemetry_change_control"`
	NdManagedFabrics             types.Bool   `tfsdk:"nd_managed_fabrics"`
	NumberOfApprovers            types.Int64  `tfsdk:"number_of_approvers"`
	Orchestration                types.Bool   `tfsdk:"orchestration"`
	TicketNamePrefix             types.String `tfsdk:"ticket_name_prefix"`
}
