// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_multi_cluster_connectivity

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func MultiClusterConnectivityDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"cluster_name": schema.StringAttribute{
				Required:            true,
				Description:         "The name that uniquely identifies the ND cluster datasource.",
				MarkdownDescription: "The name that uniquely identifies the ND cluster datasource.",
			},
			"hostname": schema.StringAttribute{
				Computed:            true,
				Description:         "The IP address or Hostname of the ND cluster.",
				MarkdownDescription: "The IP address or Hostname of the ND cluster.",
			},
		},
		Description:         "Datasource of the ND cluster for Multi-Cluster Connectivity in Nexus Dashboard",
		MarkdownDescription: "Datasource of the ND cluster for Multi-Cluster Connectivity in Nexus Dashboard",
	}
}

type MultiClusterConnectivityModel struct {
	ClusterName types.String `tfsdk:"cluster_name"`
	Hostname    types.String `tfsdk:"hostname"`
}
