name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  # Permission for checking out code
  contents: read

jobs:
  build:
    name: Check & Build Provider
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - run: chmod +x ./scripts/gofmtcheck.sh
      - name: gofmt Check
        run: ./scripts/gofmtcheck.sh
      - run: go mod tidy
      - name: Check go.mod and go.sum for changes
        run: git diff --exit-code go.mod go.sum
      - name: Build
        run: go build -v

  go-releaser:
    name: Dry-Run GoReleaser Check
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Unshallow
        run: git fetch --prune --unshallow
      - uses: actions/setup-go@v5
      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          install-only: true
          version: latest
      - name: GoReleaser Release Check
        run: goreleaser release --skip=publish,sign --snapshot --clean

