// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_remote_storage_location

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/boolvalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"regexp"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func RemoteStorageLocationResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"accept_host_key": schema.BoolAttribute{
				Optional:            true,
				Description:         "Indicates whether to accept host key for the remote storage location when the type is SCP or SFTP.",
				MarkdownDescription: "Indicates whether to accept host key for the remote storage location when the type is SCP or SFTP.",
				Validators: []validator.Bool{
					boolvalidator.ConflictsWith(path.MatchRoot("limit"), path.MatchRoot("alert_threshold"), path.MatchRoot("ignore_host_key_validation")),
				},
			},
			"alert_threshold": schema.Int64Attribute{
				Optional:            true,
				Description:         "The storage usage percentage that triggers an alert when exceeded. This applies only to NFS storage locations. If not specified during creation, the default value is 80. Valid values are between 1 and 100.",
				MarkdownDescription: "The storage usage percentage that triggers an alert when exceeded. This applies only to NFS storage locations. If not specified during creation, the default value is 80. Valid values are between 1 and 100.",
				Validators: []validator.Int64{
					int64validator.Between(1, 100), int64validator.ConflictsWith(path.MatchRoot("ssh_key"), path.MatchRoot("passphrase"), path.MatchRoot("username"), path.MatchRoot("password"), path.MatchRoot("ignore_host_key_validation")),
				},
			},
			"authentication_type": schema.StringAttribute{
				Computed:            true,
				Description:         "The authentication type for the remote storage location when the type is SCP or SFTP.",
				MarkdownDescription: "The authentication type for the remote storage location when the type is SCP or SFTP.",
			},
			"description": schema.StringAttribute{
				Optional:            true,
				Description:         "The description of the remote storage location.",
				MarkdownDescription: "The description of the remote storage location.",
			},
			"hostname": schema.StringAttribute{
				Required:            true,
				Description:         "The hostname or IP address of the remote storage server.",
				MarkdownDescription: "The hostname or IP address of the remote storage server.",
			},
			"ignore_host_key_validation": schema.BoolAttribute{
				Optional:            true,
				Description:         "Indicates whether to ignore host key validation for the remote storage location when the type is SCP or SFTP.",
				MarkdownDescription: "Indicates whether to ignore host key validation for the remote storage location when the type is SCP or SFTP.",
				Validators: []validator.Bool{
					boolvalidator.ConflictsWith(path.MatchRoot("limit"), path.MatchRoot("alert_threshold")),
				},
			},
			"limit": schema.StringAttribute{
				Optional:            true,
				Description:         "The storage capacity limit for the remote storage location. Valid for NFS storage type. The value should be specified in megabytes (MB) or gigabytes (GB), for example, 500GB or 1000MB.",
				MarkdownDescription: "The storage capacity limit for the remote storage location. Valid for NFS storage type. The value should be specified in megabytes (MB) or gigabytes (GB), for example, 500GB or 1000MB.",
				Validators: []validator.String{
					stringvalidator.ConflictsWith(path.MatchRoot("ssh_key"), path.MatchRoot("passphrase"), path.MatchRoot("username"), path.MatchRoot("password"), path.MatchRoot("ignore_host_key_validation")), stringvalidator.RegexMatches(regexp.MustCompile(`^[1-9][0-9]*(MB|GB)$`), "must be a positive number followed by MB or GB, for example 500GB or 1000MB"),
				},
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "The name of the remote storage location.",
				MarkdownDescription: "The name of the remote storage location.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
				Validators: []validator.String{
					stringvalidator.LengthBetween(1, 63), stringvalidator.RegexMatches(regexp.MustCompile(`^[a-z0-9]([a-z0-9-]*[a-z0-9])?(\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)*$`), "must start and end with an alphanumeric character and may contain lowercase letters, digits, hyphens, and dots"),
				},
			},
			"passphrase": schema.StringAttribute{
				Optional:            true,
				Sensitive:           true,
				Description:         "The optional passphrase associated with the private key for the remote storage location when the type is SCP or SFTP.",
				MarkdownDescription: "The optional passphrase associated with the private key for the remote storage location when the type is SCP or SFTP.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
					stringplanmodifier.UseStateForUnknown(),
				},
				Validators: []validator.String{
					stringvalidator.ConflictsWith(path.MatchRoot("password"), path.MatchRoot("limit"), path.MatchRoot("alert_threshold")),
				},
			},
			"password": schema.StringAttribute{
				Optional:            true,
				Sensitive:           true,
				Description:         "The password for the remote storage location when the type is SCP or SFTP.",
				MarkdownDescription: "The password for the remote storage location when the type is SCP or SFTP.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
					stringplanmodifier.UseStateForUnknown(),
				},
				Validators: []validator.String{
					stringvalidator.ConflictsWith(path.MatchRoot("ssh_key"), path.MatchRoot("passphrase")),
				},
			},
			"path": schema.StringAttribute{
				Required:            true,
				Description:         "The export path for NFS storage or the base path for SCP/SFTP storage on the remote server.",
				MarkdownDescription: "The export path for NFS storage or the base path for SCP/SFTP storage on the remote server.",
			},
			"port": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "The port number for connecting to the remote storage server. Default port is 2049 for NFS and 22 for SCP/SFTP. The valid range is between 1 and 65535.",
				MarkdownDescription: "The port number for connecting to the remote storage server. Default port is 2049 for NFS and 22 for SCP/SFTP. The valid range is between 1 and 65535.",
				Validators: []validator.Int64{
					int64validator.Between(1, 65535),
				},
			},
			"read_write": schema.BoolAttribute{
				Optional:            true,
				Description:         "Indicates whether the storage location is read-write or read-only. If false, the storage location is read-only.",
				MarkdownDescription: "Indicates whether the storage location is read-write or read-only. If false, the storage location is read-only.",
			},
			"ssh_key": schema.StringAttribute{
				Optional:            true,
				Sensitive:           true,
				Description:         "The private key for the remote storage location when the type is SCP or SFTP.",
				MarkdownDescription: "The private key for the remote storage location when the type is SCP or SFTP.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
					stringplanmodifier.UseStateForUnknown(),
				},
				Validators: []validator.String{
					stringvalidator.ConflictsWith(path.MatchRoot("password"), path.MatchRoot("limit"), path.MatchRoot("alert_threshold")),
				},
			},
			"storage_location_type": schema.StringAttribute{
				Required:            true,
				Description:         "The type of the remote storage location. Allowed values are \"nfs\", \"scp\", and \"sftp\".",
				MarkdownDescription: "The type of the remote storage location. Allowed values are \"nfs\", \"scp\", and \"sftp\".",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
				Validators: []validator.String{
					stringvalidator.OneOf("nfs", "scp", "sftp"),
				},
			},
			"username": schema.StringAttribute{
				Optional:            true,
				Description:         "The username for the remote storage location when the type is SCP or SFTP.",
				MarkdownDescription: "The username for the remote storage location when the type is SCP or SFTP.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
					stringplanmodifier.UseStateForUnknown(),
				},
				Validators: []validator.String{
					stringvalidator.ConflictsWith(path.MatchRoot("limit"), path.MatchRoot("alert_threshold")),
				},
			},
		},
	}
}

type RemoteStorageLocationModel struct {
	AcceptHostKey           types.Bool   `tfsdk:"accept_host_key"`
	AlertThreshold          types.Int64  `tfsdk:"alert_threshold"`
	AuthenticationType      types.String `tfsdk:"authentication_type"`
	Description             types.String `tfsdk:"description"`
	Hostname                types.String `tfsdk:"hostname"`
	IgnoreHostKeyValidation types.Bool   `tfsdk:"ignore_host_key_validation"`
	Limit                   types.String `tfsdk:"limit"`
	Name                    types.String `tfsdk:"name"`
	Passphrase              types.String `tfsdk:"passphrase"`
	Password                types.String `tfsdk:"password"`
	Path                    types.String `tfsdk:"path"`
	Port                    types.Int64  `tfsdk:"port"`
	ReadWrite               types.Bool   `tfsdk:"read_write"`
	SshKey                  types.String `tfsdk:"ssh_key"`
	StorageLocationType     types.String `tfsdk:"storage_location_type"`
	Username                types.String `tfsdk:"username"`
}
